### ISSUE TITLE
Safer date handling in BPA

### ISSUE THREAD

**Issue by aschn** [WattTime/pyiso#2]
at https://github.com/WattTime/pyiso/blob/master/pyiso/bpa.py#L31

don't allow this error to be raised:

Task pyiso.tasks.get_generation with id e5eed057-fccc-4523-a149-c8aa58a0a376 raised exception:
'TypeError("\'NoneType\' object is not iterable",)'

Task was called with args: ('BPA',) kwargs: {'latest': True, 'market': 'RT5M'}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 238, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.16.0.12/newrelic/hooks/application_celery.py", line 66, in wrapper
    return wrapped(_args, *_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 416, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/pyiso/tasks.py", line 15, in get_generation
    data = c.get_generation(*_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/pyiso/bpa.py", line 118, in get_generation
    raw_data += self._request_tsv(url, latest, start_at, end_at)
  File "/app/.heroku/python/lib/python2.7/site-packages/pyiso/bpa.py", line 43, in _request_tsv
    vals = self._preprocess(row)
  File "/app/.heroku/python/lib/python2.7/site-packages/pyiso/bpa.py", line 31, in _preprocess
    vals[0] = self._utcify(dateutil_parse(vals[0]))
  File "/app/.heroku/python/lib/python2.7/site-packages/dateutil/parser.py", line 748, in parse
    return DEFAULTPARSER.parse(timestr, *_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/dateutil/parser.py", line 310, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
TypeError: 'NoneType' object is not iterable

**Comment by ajdonnison** [comment]
Looking at this, it is very old and the code has been refactored a number of times.  I don't think it is worth keeping it open.
