### ISSUE TITLE
keyword argument yesterday does not work

### ISSUE THREAD

**Issue by mbonvini** [WattTime/pyiso#23]
When trying to run this script

```python
from pyiso import client_factory
import pandas as pd

isone = client_factory("ISONE")

data_isone = isone.get_generation(yestarday = True)
```

I get this error

```
Traceback (most recent call last):
  File "get_carbon_footprint.py", line 10, in <module>
    data_isone = isone.get_generation(yestarday = True)
  File "/usr/local/lib/python2.7/dist-packages/pyiso/isone.py", line 51, in get_generation
    raise ValueError('Either latest must be True, or start_at and end_at must both be provided.')
ValueError: Either latest must be True, or start_at and end_at must both be provided.
```

if trying 

```python
from pyiso import caiso
ca = caiso.CAISOClient()
ca.get_generation(yesterday = True)
```

I get

```
/usr/local/lib/python2.7/dist-packages/pandas/index.so in pandas.index.IndexEngine.get_loc (pandas/index.c:3824)()

/usr/local/lib/python2.7/dist-packages/pandas/index.so in pandas.index.IndexEngine.get_loc (pandas/index.c:3704)()

/usr/local/lib/python2.7/dist-packages/pandas/hashtable.so in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12349)()

/usr/local/lib/python2.7/dist-packages/pandas/hashtable.so in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12300)()

KeyError: 'Hour'
```

**Comment by aschn** [comment]
The ISONE problem is now clarified in the docs (http://pyiso.readthedocs.org/en/latest/options.html).
